version: '2'
services:

  backend:
    image: $IMAGE_DEPLOY
    ports:
      - 80:80    
    container_name: $PROJECT_NAME
    volumes:
      - ./app/:/var/www/html/
#      - ./docker/php-apache/apache/:/etc/apache2/

  mysql:
      image: mysql:5.5
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: bd_iepmae
      ports:
        - 3306:3306
      volumes:
        - ./api-proyect-colegio/docker/mysql/sql:/docker-entrypoint-initdb.d
      command: mysqld --sql_mode=""
  apirest:
    image: ronaldgcr/api-dev-node-colegio:0.0.1
    ports:
      - 8080:3000
    volumes:
      - ./api-proyect-colegio/app/:/app
    command: yarn start
